apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oc-compliance-remediate
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-compliance
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: remediate
    repoURL: https://github.com/JAORMX/compliance-operator-gitops.git
    targetRevision: test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
