---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: master
  name: 75-master-rhcos4-service-autofs-disabled
spec:
  config:
    ignition:
      version: 3.1.0
    systemd:
      units:
      - enabled: false
        mask: true
        name: autofs.service
      - enabled: false
        mask: true
        name: autofs.socket
