---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: master
  name: 75-master-rhcos4-kernel-module-freevxfs-disabled
spec:
  config:
    ignition:
      version: 3.1.0
    storage:
      files:
      - contents:
          source: data:,install%20freevxfs%20/bin/true%0A
        mode: 420
        overwrite: true
        path: /etc/modprobe.d/75-kernel_module_freevxfs_disabled.conf
