---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: master
  name: 75-master-rhcos4-coreos-audit-option
spec:
  config:
    ignition:
      version: 3.1.0
  kernelArguments:
  - audit=1
