---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: master
  name: 75-master-rhcos4-sysctl-net-ipv4-conf-default-secure-redirects
spec:
  config:
    ignition:
      version: 3.1.0
    storage:
      files:
      - contents:
          source: data:,net.ipv4.conf.default.secure_redirects%3D0%0A
        mode: 420
        overwrite: true
        path: /etc/sysctl.d/75-sysctl_net_ipv4_conf_default_secure_redirects.conf
