---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: master
  name: 75-master-rhcos4-sysctl-kernel-kexec-load-disabled
spec:
  config:
    ignition:
      version: 3.1.0
    storage:
      files:
      - contents:
          source: data:,kernel.kexec_load_disabled%3D1%0A
        mode: 420
        overwrite: true
        path: /etc/sysctl.d/75-sysctl_kernel_kexec_load_disabled.conf
