---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
  name: mcp-unpause-job
  namespace: openshift-gitops
spec:
  template:
    spec:
      containers:
        - image: registry.redhat.io/openshift4/ose-cli:v4.4
          command:
            - /bin/bash
            - -c
            - |
              export HOME=/tmp/mcp
              echo ""
              echo -n "Un-pausing MachineConfigPools."
              MCPS=("worker" "master" )
              for MCP in "${MCPS[@]}"
              do
                oc patch machineconfigpools $MCP -p '{"spec":{"paused":false}}' --type=merge
              done
              echo "DONE"
              echo -n "Waiting for the MachineConfigPools to converge."
              sleep $SLEEP
              MCPS=("worker" "master" )
              for MCP in ${MCPS[@]}
              do
                until oc wait --for condition=updated --timeout=60s mcp $MCP
                do
                  echo -n "...still waiting for $MCP to converge"
                  sleep $SLEEP
                done
              done
              echo "DONE"
          imagePullPolicy: Always
          name: mcp-unpause-job
          env:
          - name: SLEEP
            value: "5"
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      serviceAccount: mcp-job-sa
      serviceAccountName: mcp-job-sa
      terminationGracePeriodSeconds: 30
