---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: 75-worker-rhcos4-sysctl-net-core-bpf-jit-harden
spec:
  config:
    ignition:
      version: 3.1.0
    storage:
      files:
      - contents:
          source: data:,net.core.bpf_jit_harden%3D2%0A
        mode: 420
        overwrite: true
        path: /etc/sysctl.d/75-sysctl_net_core_bpf_jit_harden.conf
