---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: 75-worker-rhcos4-package-usbguard-installed
spec:
  config:
    ignition:
      version: 3.1.0
  extensions:
  - usbguard
