---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: 75-worker-rhcos4-sysctl-fs-protected-hardlinks
spec:
  config:
    ignition:
      version: 3.1.0
    storage:
      files:
      - contents:
          source: data:,fs.protected_hardlinks%3D1%0A
        mode: 420
        overwrite: true
        path: /etc/sysctl.d/75-sysctl_fs_protected_hardlinks.conf
