---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: 75-worker-rhcos4-coreos-audit-backlog-limit-kernel-argument
spec:
  config:
    ignition:
      version: 3.1.0
  kernelArguments:
  - audit_backlog_limit=8192
