---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: 75-worker-rhcos4-audit-rules-login-events-tallylog
spec:
  config:
    ignition:
      version: 3.1.0
    storage:
      files:
      - contents:
          source: data:,-w%20/var/log/tallylog%20-p%20wa%20-k%20logins%0A
        mode: 420
        overwrite: true
        path: /etc/audit/rules.d/75-tallylog_login_events.rules
